### ISSUE TITLE
Userspace log of drafts

### ISSUE THREAD

**Issue by enterprisey** [WPAFC/afch-rewrite#134]
Probably shouldn't use templates. Maybe split into subpages? There will be a slightly different set of design constraints for these logs as opposed to the well-known CSD or PROD logs because the quantity of reviews will be much higher.

**Comment by primefac** [comment]
Are we referring to the suggestion of keeping some sort of AFCH log? If so, I don't see it as being much different than  https://apersonbot.toolforge.org/afchistory/ in display - just a table of page, timestamp, and action. I don't really see the need to duplicate it on-wiki as opposed to the Toolforge page, but I do suppose there's the "deleted pages" concern as well as "what happens during those times when Toolforge is down".

**Comment by enterprisey** [comment]
Yup, just deleted pages. I've had people ask me to run AfC history for them since I can see deleted pages, but that's not a very good solution of course.

**Comment by siddharthvp** [comment]
How about rejigging the afchistory tool so that it executes the API calls in the backend using an admin account so that non-admin users on the frontend can see data for deleted pages too? This will also make the tool faster since admin accounts can query 5000 page results at a time rather than 500. I don't think there should be any security issue – especially if you use a botpassword or [owner-only OAuth credential](https://www.mediawiki.org/wiki/OAuth/Owner-only_consumers) with only the required rights, and restricted to the Toolforge IP addresses. - [SD0001 on-wiki]

**Comment by enterprisey** [comment]
That's a good idea! I tried thinking about privacy/whatever justifications as to why using an admin account wouldn't work, but I guess it's fine. Will look into this at some point.

**Comment by NovemLinguae** [comment]
I think an AFC log in one's userspace is a decent idea. Twinkle logs CSD, PROD, and XFD, so AFC seems like a reasonable thing to log.

**Comment by kzhovn** [comment]
I'm partway through implementing this (for some reason it respects preferences fine when I set the default to on but not when off). I've tentatively set the message to 

> \n# [Accept/reject/decline]ing [[:Title]] by [[User:Username|]] ~~~~~\n

Thoughts? I'm considering adding a the reject/decline reason but I don't want to get too verbose.

**Comment by primefac** [comment]
If you're going to leave the decline reason, use the code itself (e.g. `cv` or `adv`). Otherwise, I like the short/concise prose you've given. However, I'd make your suffix "ed" instead of "ing" since it's a log and therefore in the past tense.

**Comment by kzhovn** [comment]
New message for decline only (not reject):
> \n# Declined [[:Title]] (reason1 & reason2) by [[User:Username|]] ~~~~~\n
