### ISSUE TITLE
Remove some biography text boxes from accept screen?

### ISSUE THREAD

**Issue by NovemLinguae** [WPAFC/afch-rewrite#170]
When accepting a draft and checking the biography check box, this displays additional text boxes that collect information. It seems like some of these may be unused. Consider examining the code to see if they are unused, then removing them.

Possibly unused:
* Description - or instead of removing this one, could have this add a {{short description}} instead
* Place of birth
* Place of death
* Month and day of birth
* Month and day of death

Someone said this data might be sent to Wikidata?

Discussion:
https://en.wikipedia.org/wiki/Wikipedia_talk:WikiProject_Articles_for_creation#Question_About_Person_Dates

Note: I am not just creating all these tickets to spam you guys. Someday I hope to make fixing all this stuff a project of mine and submit a bunch of pull requests. These tickets will give me ideas of stuff to fix :)

**Comment by primefac** [comment]
See also https://en.wikipedia.org/wiki/Wikipedia_talk:WikiProject_Articles_for_creation/2020_2#Place_of_Birth in which it was mentioned that these used to be used, but the templates using the information don't exist any more and thus these values are not stored anywhere.

**Comment by robertsky** [comment]
Description: Agreed that this can be used for {{short description}} instead. 

Place of birth/death, month and day of birth/death
To summarise what I have read through [TfDs](https://en.wikipedia.org/wiki/Wikipedia:Templates_for_discussion/Log/2016_June_26#Template:Persondata) and [RfC](https://en.wikipedia.org/wiki/Wikipedia:Village_pump_(proposals)/Archive_122#RfC:_Should_Persondata_template_be_deprecated_and_methodically_removed_from_articles?), all these were for [Persondata template](https://en.wikipedia.org/wiki/Wikipedia:Persondata), which has since superseded by Wikidata. Clearly we are not sending these to Wikidata. If we want to send to Wikidata, we will need to establish a link to either existing Wikidata entry, or create new Wikidata entry during the approval flow. Not sure if the wider reviewer pool wants to include finding Wikidata entries during the review flow.

An alternative I can think of it to create/update the Infobox person template with these values.

I suggest removing the place of birth/death, month and day of birth/death fields for now to minimise on the number of unnecessary fields filled up by reviewers.
