### ISSUE TITLE
Use a simple HTTP dev server

### ISSUE THREAD

**Issue by siddharthvp** [WPAFC/afch-rewrite#193]
Is there a reason to use an HTTPS server for localhost development? I don't know if it made sense in the 2010s when it was put in place, but don't think it makes any sense now. An http server is very easy to work with - no need to generate certs or install them into the browser or anything.

**Comment by enterprisey** [comment]
@siddharthvp I originally went with https because I thought the http approach was insecure (because you have to do some sort of messing around with flags). But I'm no web developer, so if you think it'll be fine (and it's the standard way to do things) then I'm all for it. Clearly a lot of people are having issues with it and if they're wasting their time we better get that obstacle out of their way ASAP.

**Comment by enterprisey** [comment]
alright gonna swap the instructions and everything to http now

**Comment by siddharthvp** [comment]
> I thought the http approach was insecure (because you have to do some sort of messing around with flags)

no flag changes are needed (or at least I've never had to do any flag changes on Chrome/Firefox on Windows/Mac/Linux -- I've used them all at some point :D)

**Comment by enterprisey** [comment]
739b17d36e542117f260c13e98c3cbc331b3fcf5
