### ISSUE TITLE
Previewing decline reasons

### ISSUE THREAD

**Issue by APerson241** [WPAFC/afch-rewrite#46]
It would be great if we could preview decline reasons.

Perhaps something like putting a (preview) link on the right side of the selection dropdown, without throwing off the center alignment and at 80% font size.

**Comment by Lorwp** [comment]
If wikicode is supported inside the interface, we could do something like ```{{collapse|1=collapsed text|2=Preview of template}}``` and style it accordingly with custom CSS to make it slightly more transparent and more "Fit" with the style that may be wanted in the interface. Otherwise a collapsed box could be created manually (not too sure of the CSS and JS implications of doing such) with some sort of way to request the html of the templates with the relevant fields (E.g: Usernames) filled out.

**Comment by APerson241** [comment]
I was just thinking of sucking the HTML out of Template:AfC submissions/comments and sticking that inside a styled div, but that can work too.

**Comment by Lorwp** [comment]
oh...maybe i over-complicated things in my way :P

**Comment by APerson241** [comment]
To add on, previewing the custom comments left along with a decline would also be really great.

Looking into Parsoid right now.

**Comment by APerson241** [comment]
I have this working on my box, by the way... just finishing it up right now. Should have it out by tomorrow.

**Comment by APerson241** [comment]
See the pull request in #77.
