### ISSUE TITLE
Script freezes when automatically opening

### ISSUE THREAD

**Issue by APerson241** [WPAFC/afch-rewrite#47]

**Comment by Lorwp** [comment]
As i reported this on IRC, i'll quickly add something here.

Pretty much the issue here is that when the option in preferences ```Automatically open the review panel on AfC submissions``` is ticked it freezes on this screen, and stays there unless you restart it.
![untitled](https://cloud.githubusercontent.com/assets/8052896/6121055/0f5470a4-b131-11e4-94f9-a4ad6f10f5a5.png)

**Comment by theopolisme** [comment]
Uncaught ReferenceError: Hogan is not defined
load.php?debug=false&lang=en&modules=jquery%2Cmediawiki&only=scripts&skin=vector&version=20150205T2…:154

Looks like the hogan.js file might not be being loaded?

**Comment by Lorwp** [comment]
Possibly, if i get a chance i'll use my (Admittedly limited) knowledge of the AFCH code to try and (Admittedly probably not very well) fix it.

**Comment by theopolisme** [comment]
Fixed & live
