### ISSUE TITLE
Custom rationale not visable

### ISSUE THREAD

**Issue by josve05a** [WPAFC/afch-rewrite#63]
https://en.wikipedia.org/w/index.php?title=Draft:Professor_Alexia_Thomas&diff=669966356&oldid=669927520

**Comment by josve05a** [comment]
Due to an external link with an equality sign in it. the part before that is interpreted as a parameter name, the part afterwards as the value of that template parameter, making the entire rational invincible, since no such parameter name exists.

**Comment by theopolisme** [comment]
I thought this was a weird bug, because I could have sworn I added a conditional to handle the case of "equals sign in template value" and switch to using an absolute parameter instead. Turns out I did, but some missing parentheses somewhat stymied the effort :) Now fixed and will be live shortly. Cheers,
