### ISSUE TITLE
Participants list check should be partially case-insensitive

### ISSUE THREAD

**Issue by Commissar0617** [WPAFC/afch-rewrite#85]
gives me the "you're not listed as a contrubutor" error. but i've been lidted for several months now....
also posted on the talk page about it.

**Comment by Commissar0617** [comment]
suspect it has something to do with strict capitalization.

**Comment by Commissar0617** [comment]
yep. it's probably because you use (if im reading it correctly) an indexOf function. not sure if it's a code issue, or an issue with whomever is adding users. maybe add a hatnote/editnote would suffice?

**Comment by Umang03** [comment]
hey ! i want to work on this issue . plz assign this to me .

**Comment by enterprisey** [comment]
Instructions:
1. Change the line `whitelistRequired: mw.config.get( 'wgDBname' ) !== 'testwiki'` in src/modules/core.js to `whitelistRequired: true`
2. Verify that you are unable to review drafts, such as by going to the test draft you created at test.wikipedia.org/Special:MyPage/draft during the [developer setup](https://en.wikipedia.org/wiki/Wikipedia:WikiProject_Articles_for_creation/Helper_script/Contributing/Developer_setup)
3. Add yourself to https://test.wikipedia.org/wiki/Wikipedia:WikiProject_Articles_for_creation/Participants, matching the format of existing entries.
4. Verify that you are now able to use the script.
5. Change the first letter of your username in https://test.wikipedia.org/wiki/Wikipedia:WikiProject_Articles_for_creation/Participants to lowercase. Verify that you cannot use the script any more (that is, you get the popup error).
6. Modify the `checkWhitelist` function in src/modules/core.js to replace the first letter of the user's name (in sanitizedUser) with a fragment of a regular expression, so that the first letter can be uppercase or lowercase. Only do this if the first letter is an ASCII letter, because it looks like JavaScript doesn't handle other character sets well.
7. Verify that you can now use the script again

**Comment by enterprisey** [comment]
Background information: The page "Wikipedia:WikiProject Articles for creation/Participants" is used to list users who have been approved to use the script. Administrators add new user names to that page following the existing format. Sometimes administrators add usernames with the wrong case. On Wikipedia, user names are case-**insensitive** for just the first letter (enterprisey and Enterprisey are the same), but case-sensitive for the other letters (enterprisey and eNterprisey and enterpriseY are all different). In this case, an administrator added a user with a lowercase name, which had to be fixed in this edit: https://en.wikipedia.org/w/index.php?title=Wikipedia:WikiProject_Articles_for_creation/Participants&diff=prev&oldid=813681198&diffmode=source

**Comment by primefac** [comment]
Personally, I don't think this is a bug that needs fixing - a list of usernames _should_ be specific to the way the name is displayed in the URL.

**Comment by enterprisey** [comment]
Sounds fine; closing.
